export { default as Footer } from './Footer/Footer';
export { default as Form } from './Form/Form';
export { default as Login } from './Form/Login/Login';
export { default as Register } from './Form/Register/Register';
export { default as User } from './Form/Register/User/User';
export * from './Form/validator';
export { default as Home } from './Home/Home';
export { default as LandingPage } from './LandingPage/LandingPage';
export { default as NavBar } from './NavBar/NavBar';
export * from './index';
